version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: animal_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - animal_network_01
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-server
    restart: always
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - animal_network_01
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/postgres?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user

networks:
  animal_network_01:


