session:
  setMaxInactiveInterval: 1800
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  messages:
    basename: messages,errors
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    whitelabel:
      enabled: 'true'
file:
  dir: C:/Users/setby/animal/file/
